# Generated by Django 4.2.11 on 2024-05-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('agency_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('gst_no', models.CharField(max_length=30)),
                ('upi_id', models.CharField(max_length=30)),
                ('agency_logo', models.ImageField(upload_to='agency_logo/')),
                ('about_us', models.TextField()),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
