# Generated by Django 4.2.11 on 2024-05-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='total_price',
            field=models.FloatField(default=50),
            preserve_default=False,
        ),
    ]
